language: python
sudo: false
services:
    - mysql
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS zmysqldatest CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -e "CREATE USER 'zmysqldatest'@'localhost' IDENTIFIED BY 'zmysqldatest';"
  - mysql -e "GRANT ALL PRIVILEGES ON zmysqldatest.* TO 'zmysqldatest'@'localhost';"
  - mysql -e "SHOW VARIABLES LIKE 'character_set%';"
  - mysql -e "SHOW VARIABLES LIKE 'collation%';"
install:
    - pip install -U setuptools==33.1.1
    - pip install zc.buildout
    - pip install -U coverage coveralls
    - pip install -U six==$(curl $(awk '$1 ==  "extends" {print $3}' buildout.cfg) 2>/dev/null | awk '$1 == "six" {print $3}')
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v1
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
